Document: tmuxpackage
Title: Debian tmuxpackage Manual
Author: <insert document author here>
Abstract: This manual describes what tmuxpackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tmuxpackage/tmuxpackage.sgml.gz

Format: postscript
Files: /usr/share/doc/tmuxpackage/tmuxpackage.ps.gz

Format: text
Files: /usr/share/doc/tmuxpackage/tmuxpackage.text.gz

Format: HTML
Index: /usr/share/doc/tmuxpackage/html/index.html
Files: /usr/share/doc/tmuxpackage/html/*.html
